DROP TABLE pqr_accesstokens;
DROP TABLE pqr_achievements;
DROP TABLE pqr_csc;
DROP TABLE pqr_cscorder;
DROP TABLE pqr_raidaccess;
DROP TABLE pqr_raids;
DROP TABLE pqr_roles;
DROP TABLE pqr_signups;
DROP TABLE pqr_unavail;
DROP TABLE pqr_weeks;
-- 2.0;
DROP TABLE pqr_rank_list;
DROP TABLE pqr_ranks;
